[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Nicky van Urk <info@nickyvanurk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
lazy_static = "1.4.0"
regex = "1.5.4"
